default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
  - repo: https://github.com/golangci/golangci-lint
    rev: 77a8601aa372eaab3ad2d7fa1dffa71f28005393  # frozen: v1.57.2
    hooks:
      - id: golangci-lint-full
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 4055bbb444ea66dca166828d6bc11bf7ba7fc157  # frozen: v3.14.1
    hooks:
      - id: commitizen
        stages:
          - commit-msg
